# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/.packages"
    schedule: { interval: "daily" }
    open-pull-requests-limit: 10
    labels: [ "dependencies", "untracked work" ]
    commit-message: { prefix: "chore", include: "scope" }
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    groups:
      GraphQL:
        patterns:
          - "HotChocolate.*"
      DataAccess:
        patterns:
          - "Microsoft.EntityFrameworkCore.*"
      MassTransit:
        patterns:
          - "MassTransit"
          - "MassTransit.*"
      Logging:
        patterns:
          - "Serilog.*"
      Caching:
        patterns:
          - "ZiggyCreatures.*"
      Remaining:
        patterns:
          - "*"
        exclude-patterns:
          - "HotChocolate*"
          - "MassTransit*"
          - "Serilog.*"
          - "ZiggyCreatures.*"
          - "Microsoft.EntityFrameworkCore.*"
