name: 'Update Lockfiles'
description: 'Force restore and commit updated NuGet lock files for Dependabot NuGet PRs'

runs:
  using: 'composite'
  steps:
    - name: Force restore
      shell: bash
      run: dotnet restore --force-evaluate

    - name: Commit and Push Changes
      shell: bash
      run: |
        set -euo pipefail
        git config --global user.name 'dependabot[bot]'
        git config --global user.email 'support@github.com'
        
        echo '*****STARTING LOCKFILE SYNC*****'
        git branch --show-current
        git add -A
        git status
        git commit -m 'Update lock files' || echo 'No changes to commit'
        BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
        echo "The branch name is $BRANCH_NAME"
        git push