name: 'Update Lockfiles'
description: 'Force restore and commit updated NuGet lock files for Dependabot PRs'

runs:
  using: 'composite'
  steps:
    - name: Force restore
      shell: bash
      run: |
        echo "work space: $GITHUB_WORKSPACE"
        dotnet restore --force-evaluate --packages "$GITHUB_WORKSPACE/../.nuget"

    - name: Commit and Push Changes
      shell: bash
      run: |
        set -euo pipefail
        git config --global user.name 'dependabot[bot]'
        git config --global user.email 'support@github.com'

        echo "cuurrent branch: $(git branch --show-current)"
        git add -A
        git status
        git commit -m 'Update lock files' || echo 'No changes to commit'
        git push