# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  auto-sync:
    name: Auto Sync Lock Files (Dependabot only)
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' && startsWith(github.head_ref, 'dependabot/nuget/')
    uses: ./.github/workflows/nuget-lockfile-sync.yml

  build:
    name: Build
    needs: [auto-sync]
    runs-on: ubuntu-latest
    if: needs.auto-sync.result != 'failure' && (needs.auto-sync.outputs.commit_pushed != 'true')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.304
      - name: Restore dependencies
        run: dotnet restore --locked-mode
      - name: Build
        run: dotnet build --no-restore
