# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.304

      - name: Auto Update Lock Files (for Dependabot PRs)
        if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' && startsWith(github.head_ref, 'dependabot/nuget/')
        uses: ./.github/actions/update-lockfiles    

      - name: Restore dependencies
        run: |
          echo "work space: $GITHUB_WORKSPACE"
          echo "{{ github.workspace }}"
          dotnet restore --locked-mode --packages "$GITHUB_WORKSPACE/../.nuget"

      - name: Build
        run: dotnet build --no-restore
