name: Auto Sync Lock Files

on:
  push:
    branches:
      - 'dependabot/nuget/**'

permissions:
  actions: read
  contents: write
  packages: read
  checks: write
  pull-requests: write

jobs:
  update-lock-files:
    name: Auto Sync Lock Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.304

      - name: Force restore
        run: dotnet restore --force-evaluate

      - name: Commit and Push Changes
        id: sync_commit
        shell: bash
        run: |
          set -euo pipefail
          git config --global user.name 'dependabot[bot]'
          git config --global user.email 'support@github.com'

          echo '*****STARTING*****'
          git branch --show-current
          git status
          git add -A
          git commit -m 'Update lock files' || echo "No changes to commit"

          # Use GITHUB_HEAD_REF for PR branch name, not GITHUB_REF
          BRANCH_NAME="${{ github.ref }}"
          echo "The branch name is $BRANCH_NAME"
          git push
